# Generated by Django 4.1.3 on 2022-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='media/post_img/%Y/%m/%d'),
        ),
    ]
